### ISSUE TITLE
Features required for a minimal governance testnet

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#14]
MUST HAVE:
For A DEVNET we can test voting with SPO keys: 

- [ ] [A command to create governance actions](https://github.com/input-output-hk/cardano-cli/issues/6)
- [ ] [Create an Constitution Update governance action](https://github.com/input-output-hk/cardano-cli/issues/52)
- [ ] [Create VOTES on Governance actions](https://github.com/input-output-hk/cardano-cli/issues/10)
- [ ] [Modify BUILD-RAW command to take vote and action files to build a transaction body](https://github.com/input-output-hk/cardano-cli/issues/12)
- [ ] [Modify BUILD command to take vote and action files to build a transaction body](https://github.com/input-output-hk/cardano-cli/issues/13)

GOOD TO HAVE:
- [ ] [A command to inspect an action file produced with "cardano-cli governance action"](https://github.com/input-output-hk/cardano-cli/issues/8)
- [ ] [Inspect/View a vote file](https://github.com/input-output-hk/cardano-cli/issues/11)
- [ ] [QUERY on-chain governance actions](https://github.com/input-output-hk/cardano-cli/issues/9)

**Comment by CarlosLopezDeLara** [comment]
Related PR #15

**Comment by kevinhammond** [comment]
I'd have thought you don't **absolutely need** the explicit query (though it's nice to have, especially for devnet) - the chain state can be inspected easily by a chain follower - state queries generally are not really supported by ledger, are they?

You also don't need separate ways to create governance actions and constitution update actions - you probably want the general one and for it to work for constitution updates?

When you say create VOTES/create ACTIONS you are really referring to the vote/action files that you're embedding in build-raw, of course

**Comment by CarlosLopezDeLara** [comment]
@kevinhammond 

- Included the query command exactly because of the devnet, it would simplify demonstration and I assume it should be possible since ledger must keep track of active actions anyways. The devnet I have in mind is very minimal (even a short lived local cluster) so ledger state should be really quick to query. Although it might not be strictly needed as you said. so moving it to nice to have. 

- Agreed there is no 2 separate ways to create gov actions and constitution-updates actions. `actions` is a subcommand of `governance` and ` create-constitutional-update` a subcommand of `actions` so it looks like this:

If you run  `cardano-cli governance action` you access the help for action which should show: 

```
cardano-cli governance action 
            ( create-no-confidence-motion
            | create-new-committee
            | create-constitution-update
            | create-hard-fork-initiation
            | create-protocol-parameter-update
            | create-treasury-withdrawal 
            | create-info
            | view
            | query
            )
```
            
and if you run `cardano-cli governance action create-constitution-update`  you access the help for that: 
            
```
cardano-cli governance action create-constitution-update
--proposal-url  URL
--proposal-hash STRING
--out-file
```
- Exactly right the output is the file you later use on build/build-raw
