### ISSUE TITLE
adjust cc-resignation certificate to also include an optional anchor

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-cli#384]
Committee member resignation certificate now may include an anchor as of https://github.com/input-output-hk/cardano-ledger/pull/3794

Currently we have:

```
Usage: cardano-cli conway governance committee create-cold-key-resignation-certificate 
                                                                                         ( --cold-verification-key STRING
                                                                                         | --cold-verification-key-file FILE
                                                                                         | --cold-verification-key-hash STRING
                                                                                         )
                                                                                         --out-file FILE
```

so, `cardano-cli ` needs to also include the option of passing an optional anchor. 

## Roadmap to fix

- [x] Have a `ledger` release done after https://github.com/input-output-hk/cardano-ledger/pull/3794
- [x] Update `cardano-ledger` in `cardano-cli`
- [ ] Write and merge a PR dedicated to this issue - _Cancelled_, see comments

**Comment by smelc** [comment]
Actually this was done by @teodanciu in https://github.com/input-output-hk/cardano-cli/pull/385 :partying_face:

See, at 978763480b017ca8d3231da51cd46e973ea417f4, the new API of `create-cold-key-resignation-certificate`:

```shell
→ cabal run cardano-cli -- conway governance committee create-cold-key-resignation-certificate 
Usage: cardano-cli conway governance committee create-cold-key-resignation-certificate 
                                                                                         ( --cold-verification-key STRING
                                                                                         | --cold-verification-key-file FILE
                                                                                         | --cold-verification-key-hash STRING
                                                                                         )
                                                                                         [--resignation-metadata-url TEXT
                                                                                           --resignation-metadata-hash HASH]
                                                                                         --out-file FILE

  Create cold key resignation certificate for a Constitutional Committee Member

Available options:
  --cold-verification-key STRING
                           Constitutional Committee cold key (hex-encoded).
  --cold-verification-key-file FILE
                           Filepath of the Consitutional Committee cold key.
  --cold-verification-key-hash STRING
                           Constitutional Committee key hash (hex-encoded).
  --resignation-metadata-url TEXT
                           Constitutional Committee cold key resignation
                           certificate URL
  --resignation-metadata-hash HASH
                           Constitutional Committee cold key resignation
                           certificate metadata hash
  --out-file FILE          The output file.
  -h,--help                Show this help text
```
