### ISSUE TITLE
Follow-ups on create-testnet-data v1

### ISSUE THREAD

**Issue by smelc** [input-output-hk/cardano-cli#506]
## Roadmap

- [x] https://github.com/input-output-hk/cardano-cli/issues/473#issuecomment-1828297866 (see also https://input-output-rnd.slack.com/archives/C031GFLC3DF/p1701118783237699) → Done in https://github.com/input-output-hk/cardano-cli/pull/512
- [ ] https://github.com/input-output-hk/cardano-cli/pull/488#discussion_r1411731739
- [ ] https://github.com/input-output-hk/cardano-cli/issues/473#issuecomment-1824238007
- [X] Discuss the desired meaning of the `--supply` and the `--supply-delegated` flags. Do we want to keep the previous behavior that the total supply is `--supply` plus `--supply-delegated`?  Or do we want `--supply` to be the real total supply and the non delegated supply to be `--supply` minus `--supply-delegated`? → Done in https://github.com/IntersectMBO/cardano-cli/pull/581
- [x] Use `create-testnet-data` instead of `create-staked` in cardano-node [here](https://github.com/input-output-hk/cardano-node/blob/e0fbe45fcd7f6a08327b48e886dc9cc9d4f8faf8/cardano-testnet/src/Testnet/Components/Configuration.hs#L117).
- [ ] Simplify the computation of the `distribution`: https://github.com/input-output-hk/cardano-cli/pull/512#discussion_r1423848579

## Additional context

The first item above is kind about reintroducing https://github.com/input-output-hk/cardano-node/pull/4021, but behind a conditional flag:
  
> Discussing this with @Jimbo4350 he came up with a glorious idea of having an option to write (or not) the delegated keys to disk. The current behavior is that it does not write them to disk after a request from the benchmarking team. Having this as an option gives us more flexibility for other use cases (i.e. tests) where we do need the stake keys available.

The last item above is about [this remark](https://github.com/input-output-hk/cardano-cli/pull/512#discussion_r1423848579) from @carlhammann :

> I can't comment directly on the line, because it's not (yet 😛) part of the diff, but the definition of distribution in the next line is an atrocity, IMO. It should be
>
>```
>distribution = concat $ zipWith (\params poolIx -> replicate (delegsForPool poolIx) params) >poolParams [1..]
>```
> or something similar, instead of relying on the semantics of list comprehensions with unused parameters.

**Comment by smelc** [comment]
Closing as remaining improvements and checks have been done by @palas (see https://github.com/IntersectMBO/cardano-cli/pull/646) and others the last weeks.
